// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  education: create.doc("education", {"bcc.mdx": () => import("../content/education/bcc.mdx?collection=education"), "dsh.mdx": () => import("../content/education/dsh.mdx?collection=education"), "eli.mdx": () => import("../content/education/eli.mdx?collection=education"), "hs-mittweida.mdx": () => import("../content/education/hs-mittweida.mdx?collection=education"), "sf-state.mdx": () => import("../content/education/sf-state.mdx?collection=education"), }),
  experience: create.doc("experience", {"driver.mdx": () => import("../content/experience/driver.mdx?collection=experience"), "mercedes-benz.mdx": () => import("../content/experience/mercedes-benz.mdx?collection=experience"), "morningstar.mdx": () => import("../content/experience/morningstar.mdx?collection=experience"), "renewable-energy.mdx": () => import("../content/experience/renewable-energy.mdx?collection=experience"), "self-employed-android-early-2012.mdx": () => import("../content/experience/self-employed-android-early-2012.mdx?collection=experience"), "self-employed-android-early.mdx": () => import("../content/experience/self-employed-android-early.mdx?collection=experience"), "self-employed-android.mdx": () => import("../content/experience/self-employed-android.mdx?collection=experience"), "self-employed-frontend-2025.mdx": () => import("../content/experience/self-employed-frontend-2025.mdx?collection=experience"), "self-employed-frontend.mdx": () => import("../content/experience/self-employed-frontend.mdx?collection=experience"), "tesla-material-handler.mdx": () => import("../content/experience/tesla-material-handler.mdx?collection=experience"), "tesla-production-associate.mdx": () => import("../content/experience/tesla-production-associate.mdx?collection=experience"), "unitel.mdx": () => import("../content/experience/unitel.mdx?collection=experience"), }),
  pages: create.doc("pages", {"about.mdx": () => import("../content/pages/about.mdx?collection=pages"), }),
  projects: create.doc("projects", {"full-stack-blog-app.mdx": () => import("../content/projects/full-stack-blog-app.mdx?collection=projects"), "local-market-place-app.mdx": () => import("../content/projects/local-market-place-app.mdx?collection=projects"), "portfolio-app-java.mdx": () => import("../content/projects/portfolio-app-java.mdx?collection=projects"), "portfolio-app-kotlin.mdx": () => import("../content/projects/portfolio-app-kotlin.mdx?collection=projects"), "portfolio-website-v0.mdx": () => import("../content/projects/portfolio-website-v0.mdx?collection=projects"), "portfolio-website-v1.mdx": () => import("../content/projects/portfolio-website-v1.mdx?collection=projects"), "portfolio-website-v2.mdx": () => import("../content/projects/portfolio-website-v2.mdx?collection=projects"), "portfolio-website-v3.mdx": () => import("../content/projects/portfolio-website-v3.mdx?collection=projects"), "product-landing-page.mdx": () => import("../content/projects/product-landing-page.mdx?collection=projects"), "project-marketing-materials.mdx": () => import("../content/projects/project-marketing-materials.mdx?collection=projects"), "renewable-energy-project.mdx": () => import("../content/projects/renewable-energy-project.mdx?collection=projects"), "runmusic-kotlin.mdx": () => import("../content/projects/runmusic-kotlin.mdx?collection=projects"), "sign-language-kotlin.mdx": () => import("../content/projects/sign-language-kotlin.mdx?collection=projects"), "tshirt-design-app.mdx": () => import("../content/projects/tshirt-design-app.mdx?collection=projects"), }),
};
export default browserCollections;